version: "3.7"

services:

    mariadb:
        image: mariadb:10.4
        restart: always
        ports:
            - 3307:3306
        volumes:
            - ./docker/data/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 9090:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        depends_on:
            - mariadb

    elasticsearch:
        image: nshou/elasticsearch-kibana
        ports:
            - 5601:5601

volumes:
    mariadb-data: