index:
    path: /
    controller: App\Controller\IndexController::index

elasticsearch:
    path: /elasticsearch
    controller: App\Controller\ElasticSearchController::index

like:
    path: /like
    controller: App\Controller\LikeController::index
